/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AreaInfo from './AreaInfo';

/**
 * The Area model module.
 * @module model/Area
 * @version 1.0.0
 */
class Area {
    /**
     * Constructs a new <code>Area</code>.
     * @alias module:model/Area
     * @param info {module:model/AreaInfo} 
     */
    constructor(info) { 
        
        Area.initialize(this, info);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, info) { 
        obj['info'] = info;
    }

    /**
     * Constructs a <code>Area</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Area} obj Optional instance to populate.
     * @return {module:model/Area} The populated <code>Area</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Area();

            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = AreaInfo.constructFromObject(data['info']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} parent
 */
Area.prototype['parent'] = undefined;

/**
 * @member {module:model/AreaInfo} info
 */
Area.prototype['info'] = undefined;






export default Area;

