/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AreaType from './AreaType';
import I18N from './I18N';
import LanguageRation from './LanguageRation';
import MunicipalityType from './MunicipalityType';

/**
 * The AreaInfo model module.
 * @module model/AreaInfo
 * @version 1.0.0
 */
class AreaInfo {
    /**
     * Constructs a new <code>AreaInfo</code>.
     * @alias module:model/AreaInfo
     * @param identifier {String} 
     * @param abbreviation {module:model/I18N} 
     * @param areaType {module:model/AreaType} 
     */
    constructor(identifier, abbreviation, areaType) { 
        
        AreaInfo.initialize(this, identifier, abbreviation, areaType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, abbreviation, areaType) { 
        obj['identifier'] = identifier;
        obj['abbreviation'] = abbreviation;
        obj['areaType'] = areaType;
    }

    /**
     * Constructs a <code>AreaInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AreaInfo} obj Optional instance to populate.
     * @return {module:model/AreaInfo} The populated <code>AreaInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AreaInfo();

            if (data.hasOwnProperty('calculationStatus')) {
                obj['calculationStatus'] = ApiClient.convertToType(data['calculationStatus'], 'Number');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('joinedArea')) {
                obj['joinedArea'] = ApiClient.convertToType(data['joinedArea'], 'Boolean');
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = I18N.constructFromObject(data['abbreviation']);
            }
            if (data.hasOwnProperty('municipalityType')) {
                obj['municipalityType'] = MunicipalityType.constructFromObject(data['municipalityType']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = I18N.constructFromObject(data['name']);
            }
            if (data.hasOwnProperty('areaType')) {
                obj['areaType'] = AreaType.constructFromObject(data['areaType']);
            }
            if (data.hasOwnProperty('languageRation')) {
                obj['languageRation'] = LanguageRation.constructFromObject(data['languageRation']);
            }
            if (data.hasOwnProperty('numberOfPollingDistricts')) {
                obj['numberOfPollingDistricts'] = ApiClient.convertToType(data['numberOfPollingDistricts'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} calculationStatus
 */
AreaInfo.prototype['calculationStatus'] = undefined;

/**
 * @member {String} identifier
 */
AreaInfo.prototype['identifier'] = undefined;

/**
 * @member {Boolean} joinedArea
 */
AreaInfo.prototype['joinedArea'] = undefined;

/**
 * @member {module:model/I18N} abbreviation
 */
AreaInfo.prototype['abbreviation'] = undefined;

/**
 * @member {module:model/MunicipalityType} municipalityType
 */
AreaInfo.prototype['municipalityType'] = undefined;

/**
 * @member {module:model/I18N} name
 */
AreaInfo.prototype['name'] = undefined;

/**
 * @member {module:model/AreaType} areaType
 */
AreaInfo.prototype['areaType'] = undefined;

/**
 * @member {module:model/LanguageRation} languageRation
 */
AreaInfo.prototype['languageRation'] = undefined;

/**
 * @member {Number} numberOfPollingDistricts
 */
AreaInfo.prototype['numberOfPollingDistricts'] = undefined;






export default AreaInfo;

