/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AreaType.
* @enum {}
* @readonly
*/
export default class AreaType {
    
        /**
         * value: "COUNTRY"
         * @const
         */
        "COUNTRY" = "COUNTRY";

    
        /**
         * value: "ELECTORAL_DISTRICT"
         * @const
         */
        "ELECTORAL_DISTRICT" = "ELECTORAL_DISTRICT";

    
        /**
         * value: "REGION"
         * @const
         */
        "REGION" = "REGION";

    
        /**
         * value: "MUNICIPALITY"
         * @const
         */
        "MUNICIPALITY" = "MUNICIPALITY";

    
        /**
         * value: "POLLING_DISTRICT"
         * @const
         */
        "POLLING_DISTRICT" = "POLLING_DISTRICT";

    

    /**
    * Returns a <code>AreaType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AreaType} The enum <code>AreaType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

