/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Area from './Area';

/**
 * The AreasResponse model module.
 * @module model/AreasResponse
 * @version 1.0.0
 */
class AreasResponse {
    /**
     * Constructs a new <code>AreasResponse</code>.
     * @alias module:model/AreasResponse
     * @param areas {Array.<module:model/Area>} 
     */
    constructor(areas) { 
        
        AreasResponse.initialize(this, areas);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, areas) { 
        obj['areas'] = areas;
    }

    /**
     * Constructs a <code>AreasResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AreasResponse} obj Optional instance to populate.
     * @return {module:model/AreasResponse} The populated <code>AreasResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AreasResponse();

            if (data.hasOwnProperty('areas')) {
                obj['areas'] = ApiClient.convertToType(data['areas'], [Area]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Area>} areas
 */
AreasResponse.prototype['areas'] = undefined;






export default AreasResponse;

