/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Area from './Area';
import Nominator from './Nominator';

/**
 * The AreaResponse model module.
 * @module model/AreaResponse
 * @version 1.0.0
 */
class AreaResponse {
    /**
     * Constructs a new <code>AreaResponse</code>.
     * @alias module:model/AreaResponse
     * @param area {module:model/Area} 
     * @param nominatorCount {Number} 
     * @param candidateCount {Number} 
     * @param nominators {Array.<module:model/Nominator>} 
     * @param timestamp {String} 
     */
    constructor(area, nominatorCount, candidateCount, nominators, timestamp) { 
        
        AreaResponse.initialize(this, area, nominatorCount, candidateCount, nominators, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, area, nominatorCount, candidateCount, nominators, timestamp) { 
        obj['area'] = area;
        obj['nominatorCount'] = nominatorCount;
        obj['candidateCount'] = candidateCount;
        obj['nominators'] = nominators;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>AreaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AreaResponse} obj Optional instance to populate.
     * @return {module:model/AreaResponse} The populated <code>AreaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AreaResponse();

            if (data.hasOwnProperty('area')) {
                obj['area'] = Area.constructFromObject(data['area']);
            }
            if (data.hasOwnProperty('nominatorCount')) {
                obj['nominatorCount'] = ApiClient.convertToType(data['nominatorCount'], 'Number');
            }
            if (data.hasOwnProperty('candidateCount')) {
                obj['candidateCount'] = ApiClient.convertToType(data['candidateCount'], 'Number');
            }
            if (data.hasOwnProperty('nominators')) {
                obj['nominators'] = ApiClient.convertToType(data['nominators'], [Nominator]);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Area} area
 */
AreaResponse.prototype['area'] = undefined;

/**
 * @member {Number} nominatorCount
 */
AreaResponse.prototype['nominatorCount'] = undefined;

/**
 * @member {Number} candidateCount
 */
AreaResponse.prototype['candidateCount'] = undefined;

/**
 * @member {Array.<module:model/Nominator>} nominators
 */
AreaResponse.prototype['nominators'] = undefined;

/**
 * @member {String} timestamp
 */
AreaResponse.prototype['timestamp'] = undefined;






export default AreaResponse;

