/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CandidateMembership model module.
 * @module model/CandidateMembership
 * @version 1.0.0
 */
class CandidateMembership {
    /**
     * Constructs a new <code>CandidateMembership</code>.
     * @alias module:model/CandidateMembership
     */
    constructor() { 
        
        CandidateMembership.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CandidateMembership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CandidateMembership} obj Optional instance to populate.
     * @return {module:model/CandidateMembership} The populated <code>CandidateMembership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CandidateMembership();

            if (data.hasOwnProperty('MEMBER_OF_PARLIAMENT')) {
                obj['MEMBER_OF_PARLIAMENT'] = ApiClient.convertToType(data['MEMBER_OF_PARLIAMENT'], 'Boolean');
            }
            if (data.hasOwnProperty('MEMBER_OF_EUROPEAN_PARLIAMENT')) {
                obj['MEMBER_OF_EUROPEAN_PARLIAMENT'] = ApiClient.convertToType(data['MEMBER_OF_EUROPEAN_PARLIAMENT'], 'Boolean');
            }
            if (data.hasOwnProperty('MUNICIPAL_COUNCILOR')) {
                obj['MUNICIPAL_COUNCILOR'] = ApiClient.convertToType(data['MUNICIPAL_COUNCILOR'], 'Boolean');
            }
            if (data.hasOwnProperty('REGIONAL_COUNCILOR')) {
                obj['REGIONAL_COUNCILOR'] = ApiClient.convertToType(data['REGIONAL_COUNCILOR'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} MEMBER_OF_PARLIAMENT
 */
CandidateMembership.prototype['MEMBER_OF_PARLIAMENT'] = undefined;

/**
 * @member {Boolean} MEMBER_OF_EUROPEAN_PARLIAMENT
 */
CandidateMembership.prototype['MEMBER_OF_EUROPEAN_PARLIAMENT'] = undefined;

/**
 * @member {Boolean} MUNICIPAL_COUNCILOR
 */
CandidateMembership.prototype['MUNICIPAL_COUNCILOR'] = undefined;

/**
 * @member {Boolean} REGIONAL_COUNCILOR
 */
CandidateMembership.prototype['REGIONAL_COUNCILOR'] = undefined;






export default CandidateMembership;

