/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LanguageRation.
* @enum {}
* @readonly
*/
export default class LanguageRation {
    
        /**
         * value: "FI"
         * @const
         */
        "FI" = "FI";

    
        /**
         * value: "SV"
         * @const
         */
        "SV" = "SV";

    
        /**
         * value: "FI_SV"
         * @const
         */
        "FI_SV" = "FI_SV";

    
        /**
         * value: "SV_FI"
         * @const
         */
        "SV_FI" = "SV_FI";

    

    /**
    * Returns a <code>LanguageRation</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LanguageRation} The enum <code>LanguageRation</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

