/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Language.
* @enum {}
* @readonly
*/
export default class Language {
    
        /**
         * value: "FI"
         * @const
         */
        "FI" = "FI";

    
        /**
         * value: "SE"
         * @const
         */
        "SE" = "SE";

    
        /**
         * value: "SV"
         * @const
         */
        "SV" = "SV";

    
        /**
         * value: "EN"
         * @const
         */
        "EN" = "EN";

    

    /**
    * Returns a <code>Language</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Language} The enum <code>Language</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

