/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MunicipalityType.
* @enum {}
* @readonly
*/
export default class MunicipalityType {
    
        /**
         * value: "CITY"
         * @const
         */
        "CITY" = "CITY";

    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER" = "OTHER";

    

    /**
    * Returns a <code>MunicipalityType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MunicipalityType} The enum <code>MunicipalityType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

