/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Candidate from './Candidate';
import I18N from './I18N';
import Votes from './Votes';

/**
 * The Nominator model module.
 * @module model/Nominator
 * @version 1.0.0
 */
class Nominator {
    /**
     * Constructs a new <code>Nominator</code>.
     * @alias module:model/Nominator
     */
    constructor() { 
        
        Nominator.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Nominator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Nominator} obj Optional instance to populate.
     * @return {module:model/Nominator} The populated <code>Nominator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Nominator();

            if (data.hasOwnProperty('partyIdentifier')) {
                obj['partyIdentifier'] = ApiClient.convertToType(data['partyIdentifier'], 'String');
            }
            if (data.hasOwnProperty('nominatorNumber')) {
                obj['nominatorNumber'] = ApiClient.convertToType(data['nominatorNumber'], 'Number');
            }
            if (data.hasOwnProperty('votes')) {
                obj['votes'] = Votes.constructFromObject(data['votes']);
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = I18N.constructFromObject(data['abbreviation']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = I18N.constructFromObject(data['name']);
            }
            if (data.hasOwnProperty('electoralAllianceName')) {
                obj['electoralAllianceName'] = I18N.constructFromObject(data['electoralAllianceName']);
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
            if (data.hasOwnProperty('standardPartyNumber')) {
                obj['standardPartyNumber'] = ApiClient.convertToType(data['standardPartyNumber'], 'Number');
            }
            if (data.hasOwnProperty('candidates')) {
                obj['candidates'] = ApiClient.convertToType(data['candidates'], [Candidate]);
            }
            if (data.hasOwnProperty('electoralAllianceNumber')) {
                obj['electoralAllianceNumber'] = ApiClient.convertToType(data['electoralAllianceNumber'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} partyIdentifier
 */
Nominator.prototype['partyIdentifier'] = undefined;

/**
 * @member {Number} nominatorNumber
 */
Nominator.prototype['nominatorNumber'] = undefined;

/**
 * @member {module:model/Votes} votes
 */
Nominator.prototype['votes'] = undefined;

/**
 * @member {module:model/I18N} abbreviation
 */
Nominator.prototype['abbreviation'] = undefined;

/**
 * @member {module:model/I18N} name
 */
Nominator.prototype['name'] = undefined;

/**
 * @member {module:model/I18N} electoralAllianceName
 */
Nominator.prototype['electoralAllianceName'] = undefined;

/**
 * @member {Number} seats
 */
Nominator.prototype['seats'] = undefined;

/**
 * @member {Number} standardPartyNumber
 */
Nominator.prototype['standardPartyNumber'] = undefined;

/**
 * @member {Array.<module:model/Candidate>} candidates
 */
Nominator.prototype['candidates'] = undefined;

/**
 * @member {Number} electoralAllianceNumber
 */
Nominator.prototype['electoralAllianceNumber'] = undefined;






export default Nominator;

