/**
 * Election
 * KSF Media's election service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status.
* @enum {}
* @readonly
*/
export default class Status {
    
        /**
         * value: "ELECTED"
         * @const
         */
        "ELECTED" = "ELECTED";

    
        /**
         * value: "SUBSTITUTE"
         * @const
         */
        "SUBSTITUTE" = "SUBSTITUTE";

    
        /**
         * value: "NOT_ELECTED"
         * @const
         */
        "NOT_ELECTED" = "NOT_ELECTED";

    
        /**
         * value: "INELIGIBLE"
         * @const
         */
        "INELIGIBLE" = "INELIGIBLE";

    

    /**
    * Returns a <code>Status</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Status} The enum <code>Status</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

